### ISSUE TITLE
Mobule improvements

### ISSUE THREAD

**Issue by pi0** [bestkolobok/nuxt-jsoneditor#1]
Thanks for the nice module. Following up https://github.com/nuxt/modules/pull/400 and checking the code, I found some areas to improve.

The module can expose`JsonEditor` component using `addComponent` from `@nuxt/kit` instead of using a runtime plugin. This way, the component is only added to the bundle and chunk that actually uses it. I can understand the point of injecting runtime config. We could expose a shortcut composable like `useJSONEditor` or `useJSONEditorConfig` that makes it easily available to users. Again, still auto imported only when needed.

For types support, i would suggest adding `/types` to the `exports field and top level `types.d.ts` in `package.json` and recommend import types from `nuxt-jsoneditor/types`. As long as using `import type`, it should be safe but suggesting this could be less error prune to users that might accidentally import module in app namespace.

**Comment by bestkolobok** [comment]
Hi! 

Thanks for the comments. Regarding the first question, the idea is good. I will try to make changes today or tomorrow.

Regarding the export of types, I will try to figure it out. But I'm new in typescript, and if you could help me get it right, or contribute right changes, I'd greatly appreciate it

**Comment by bestkolobok** [comment]
Hi!

I made the changes you suggested. Registered the component using `addComponent`, and using the plugin I only transfer global options that are injected directly into the [vue3-ts-jsoneditor](https://github.com/bestkolobok/vue3-jsoneditor). Also, using a plugin, I register styles for the editor. I understand that this is not the best way, but at the moment I have not found a better solution. I plan to solve this issue in the next releases.

For easy types import I change `exports` and set export for types like this: `"./types": "./dist/types.d.ts"`. But it doesn't work propertly - impot work only forom dist folder `nuxt-jsoneditor/dist/types`. I'm looking solution for this

**Comment by bestkolobok** [comment]
Implemented dynamic creation css styles after rendering the component in the package [vue3-ts-jsoneditor](https://github.com/bestkolobok/vue3-jsoneditor) that made it possible to remove the global import css styles in the runtime `plugin` of the `nuxt-jsoneditor`

**Comment by bestkolobok** [comment]
Changed the deployment flow and move the package files from `/dist` folder to the top level. This allows you to import types:

`import type JSONEditorOptions from "nuxt-jsoneditor/types";`

and 

`import type { Content, JSONContent, JSONData, JSONEditor ... } from "nuxt-jsoneditor/module";`
