### ISSUE TITLE
Not working on Nuxt3-rc14

### ISSUE THREAD

**Issue by choiyoh** [bestkolobok/nuxt-jsoneditor#3]
Hi, I'm using this library with nuxt3-rc11 version, and they released new Stable version rc14 so I upgraded my nuxt version and it doesn't want to start because of error with this library I think. 

Kindly update library to be compatible with new Nuxt version. :)

**Comment by bestkolobok** [comment]
Hi!

If you're upgrading Nuxt version in your project, you'll also need to remove yarn.lock and node_modules to prevent conflicts with other packages.

But I have already updated the Nuxt kit package to the release version 3.0.0 which came out yesterday. So, you should already have everything working 😉
