### ISSUE TITLE
[README] Module and template naming don't match

### ISSUE THREAD

**Issue by HugoMichard** [bestkolobok/nuxt-jsoneditor#5]
Thank you for this awesome package, it does exactly what I needed for my project !

I had minor struggles when setting it up as the component name given in nuxt config file (`JsonEditor`) does not match the one indicated to use in the templates (`vue-jsoneditor`). This caused my nuxt 3 app to not find the component until I updated it in the templates to `json-editor`.

Is there a reason for this mismatch ?

I can PR a fix to avoid confusion for new users if it's not the case

**Comment by bestkolobok** [comment]
Hi @HugoMichard,
Thank you for pointing out this inconsistency! I fixed it. Also, thanks to this, I found and fixed another bug that prevented setting an alternative name for a component in the config.

**Comment by HugoMichard** [comment]
Awesome, thank you for the fix ! :pray:
